### ISSUE TITLE
accuracy_checker issue: No module named 'tensorflow'

### ISSUE THREAD

**Issue by x1aoo** [openvinotoolkit/open_model_zoo#1335]
Hi, 

When I tried to test the accuracy in with TensorFlow, I meet the problem that:
ValueError: TensorFlow isn't installed. Please, install it before using. No module named 'tensorflow'. 
While I did install tensorflow and type python and import tensorflow without any bugs.

`(tf1) [root@localhost accuracy_checker]# accuracy_check -c sample/sample_config.yml -m data/test_models -s sample
Processing info:
model: SampLeNet_example
launcher: tf
device: CPU
dataset: sample_dataset
OpenCV version: 4.3.0-openvino-2020.3.0
09:13:52 accuracy_checker ERROR: TensorFlow isn't installed. Please, install it before using. 
No module named 'tensorflow'
Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/main.py", line 258, in main
    evaluator = evaluator_class.from_configs(config_entry)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py", line 73, in from_configs
    launcher = create_launcher(launcher_config, model_name)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/launcher.py", line 200, in create_launcher
    model_name=model_name, delayed_model_loading=delayed_model_loading
  File "/opt/intel/openvino_2020.3.194/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/dependency.py", line 67, in provide
    return root_provider(*args, **kwargs)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/launcher.py", line 165, in __init__
    raise ValueError(error_message or msg)
ValueError: TensorFlow isn't installed. Please, install it before using. 
No module named 'tensorflow'
(tf1) [root@localhost accuracy_checker]# python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
import tensorflow

`
<img width="841" alt="微信截图_20200720093007" src="https://user-images.githubusercontent.com/19789999/87891321-212b8380-ca6c-11ea-9b10-49381c1ee222.png">

**Comment by maxlytkin** [comment]
@x1aoo 
Please make sure you have installed required tensorflow version. You can run >pip3 install -r <openvino_dir>/deployment_tools/model_optimizer/requirements_tf.txt 
Also, before running accuracy check, set the environment variables (if not done yet) with >source <openvino_dir>/bin/setupvars.sh

Thanks.
Best regards, Max.

**Comment by vladimir-dudnik** [comment]
@x1aoo do you have an additional questions on this?

**Comment by x1aoo** [comment]
@maxlytkin @vladimir-dudnik thanks for your help. I made it after installed the required environment!

Thanks!
Xiao
