### ISSUE TITLE
AttributeError: module 'monitors' has no attribute 'Presenter'

### ISSUE THREAD

**Issue by nadeem-nrt** [openvinotoolkit/open_model_zoo#1355]
When I run most samples, I get the following error.
`
nadeem@Nadeem-XPS:~/open_model_zoo/demos/python_demos/multi_camera_multi_target_tracking$ python multi_camera_multi_target_tracking.py -i 1.mp4 2.mp4 --config configs/person.py --m_reid person-reidentification-retail-0270.xml -m person-detection-retail-0013.xml
`

```
INFO: 2020-07-28 13:46:20: Reading configuration file configs/person.py
INFO: 2020-07-28 13:46:20: Opening file 1.mp4
INFO: 2020-07-28 13:46:21: Opening file 2.mp4
INFO: 2020-07-28 13:46:21: Creating Inference Engine
INFO: 2020-07-28 13:46:21: Initializing Inference Engine plugin for CPU 
INFO: 2020-07-28 13:46:21: Loading network
INFO: 2020-07-28 13:46:21: Preparing input blobs
INFO: 2020-07-28 13:46:21: Loading model to the plugin
INFO: 2020-07-28 13:46:21: Initializing Inference Engine plugin for CPU 
INFO: 2020-07-28 13:46:21: Loading network
INFO: 2020-07-28 13:46:21: Preparing input blobs
INFO: 2020-07-28 13:46:21: Loading model to the plugin
Traceback (most recent call last):
  File "multi_camera_multi_target_tracking.py", line 276, in <module>
    main()
  File "multi_camera_multi_target_tracking.py", line 271, in main
    run(args, config, capture, object_detector, object_recognizer)
  File "multi_camera_multi_target_tracking.py", line 132, in run
    presenter = monitors.Presenter(params.utilization_monitors, 0)
AttributeError: module 'monitors' has no attribute 'Presenter'
```

**Comment by nadeem-nrt** [comment]
Fixed it!
