### ISSUE TITLE
python3 human_pose_estimation_3d_demo.py -h

### ISSUE THREAD

**Issue by yuerunyu** [openvinotoolkit/open_model_zoo#1500]
when I run "python3 human_pose_estimation_3d_demo.py -h",
Traceback (most recent call last):
  File "human_pose_estimation_3d_demo.py", line 26, in <module>
    from modules.parse_poses import parse_poses
  File "/opt/intel/openvino_2020.4.287/deployment_tools/open_model_zoo/demos/python_demos/human_pose_estimation_3d_demo/modules/parse_poses.py", line 17, in <module>
    from pose_extractor import extract_poses
ImportError: cannot import name 'extract_poses'.

**Comment by vladimir-dudnik** [comment]
@yuerunyu have you noticed **[Prerequisites](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/python_demos/human_pose_estimation_3d_demo#prerequisites)** section in demo readme?

**Comment by vladimir-dudnik** [comment]
@yuerunyu fix done in OpenVINO 2021.1 which just was released. Do you have an additional questions on this?

**Comment by IRDonch** [comment]
Closing due to inactivity.
