### ISSUE TITLE
EOF when unpacking archive after retrieving it from cache

### ISSUE THREAD

**Issue by vurusovs** [openvinotoolkit/open_model_zoo#1679]
Looks like something in cache preparing (for faster_rcnn_resnet101_coco) went wrong, and cache contains broken archive. When I try to download model next time using prepared cache, the process breaks with EOF error:
```
========== Retrieving model/public/faster_rcnn_resnet101_coco/faster_rcnn_resnet101_coco.tar.gz from the cache

========== Unpacking model/public/faster_rcnn_resnet101_coco/faster_rcnn_resnet101_coco.tar.gz
Traceback (most recent call last):
  File "downloader.py", line 357, in <module>
    main()
  File "downloader.py", line 341, in main
    for model in models]
  File "downloader.py", line 341, in <listcomp>
    for model in models]
  File "downloader.py", line 248, in download_model
    postproc.apply(reporter, output)
  File "/home/vurusovs_local/work/open_model_zoo/tools/downloader/common.py", line 449, in apply
    shutil.unpack_archive(str(postproc_file), str(output_dir), self.format)
  File "/usr/lib/python3.5/shutil.py", line 961, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]))
  File "/usr/lib/python3.5/shutil.py", line 911, in _unpack_tarfile
    tarobj.extractall(extract_dir)
  File "/usr/lib/python3.5/tarfile.py", line 1998, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2040, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2110, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2158, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 241, in copyfileobj
    buf = src.read(BUFSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

When I try to unpack archive using `tar`, it runs into the same problem

**Comment by IRDonch** [comment]
I don't know why your cache got broken, but #1781 will help repair the cache after such incidents. If you still have a broken cache, could you test with the current `develop` branch to see if it's correctly repaired?

**Comment by vladimir-dudnik** [comment]
@vurusovs do you have additional questions or we can close this issue?
