### ISSUE TITLE
Model `yolo-v2-tiny` conversion failed

### ISSUE THREAD

**Issue by vurusovs** [openvinotoolkit/open_model_zoo#1806]
Call of converter.py for `yolo-v2-tiny` failed with next traceback:
```
Traceback (most recent call last):
  File "tmp_model/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/tools/model_converter/keras_to_tensorflow.py", line 188, in <module>
    app.run(main)
  File "/home/vurusovs_local/work/openvino/tests/stress_tests/.temp_venv/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/vurusovs_local/work/openvino/tests/stress_tests/.temp_venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tmp_model/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/tools/model_converter/keras_to_tensorflow.py", line 134, in main
    model = load_input_model(FLAGS.input_model, FLAGS.input_model_json, FLAGS.input_model_yaml, custom_objects=custom_object_dict)
  File "tmp_model/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/tools/model_converter/keras_to_tensorflow.py", line 67, in load_input_model
    model = load_model(input_model_path, custom_objects=custom_objects)
  File "/home/vurusovs_local/work/openvino/tests/stress_tests/.temp_venv/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 143, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/vurusovs_local/work/openvino/tests/stress_tests/.temp_venv/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 160, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/vurusovs_local/work/openvino/tests/stress_tests/_open_model_zoo/models/public/yolo-v2-tiny-tf/pre-convert.py", line 44, in <module>
    main()
  File "/home/vurusovs_local/work/openvino/tests/stress_tests/_open_model_zoo/models/public/yolo-v2-tiny-tf/pre-convert.py", line 41, in main
    ], check=True);
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/vurusovs_local/work/openvino/tests/stress_tests/.temp_venv/bin/python3', '--', 'tmp_model/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/tools/model_converter/keras_to_tensorflow.py', '--input_model=tmp_model/public/yolo-v2-tiny-tf/yolo-v2-tiny.h5', '--output_model=tmp_model/public/yolo-v2-tiny-tf/yolo-v2-tiny.pb']' returned non-zero exit status 1.
```

Pip list:
```
Package              Version
-------------------- ---------
absl-py              0.11.0
astor                0.8.1
cached-property      1.5.2
certifi              2020.11.8
chardet              3.0.4
decorator            4.4.2
defusedxml           0.6.0
gast                 0.2.2
google-pasta         0.2.0
graphviz             0.8.4
grpcio               1.33.2
h5py                 3.1.0
idna                 2.10
importlib-metadata   2.0.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
Markdown             3.3.3
mxnet                1.5.1
networkx             2.5
numpy                1.18.5
onnx                 1.8.0
opt-einsum           3.3.0
pip                  20.2.4
protobuf             3.14.0
PyYAML               5.3.1
requests             2.25.0
setuptools           50.3.2
six                  1.15.0
tensorboard          1.15.0
tensorflow           1.15.2
tensorflow-estimator 1.15.1
termcolor            1.1.0
test-generator       0.1.1
typing-extensions    3.7.4.3
urllib3              1.26.2
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
zipp                 3.4.0
```

**Comment by IRDonch** [comment]
This is tensorflow/tensorflow#44467. Looks like the workaround is to downgrade to `h5py<3`. Alternatively, TensorFlow 2.4.0 will include a workaround.

**Comment by vurusovs** [comment]
> This is [tensorflow/tensorflow#44467](https://github.com/tensorflow/tensorflow/issues/44467). Looks like the workaround is to downgrade to `h5py<3`. Alternatively, TensorFlow 2.4.0 will include a workaround.

Do you have a plan to make some WA in OMZ requirements.in? 

If no, I will close issue and do it on my side

**Comment by IRDonch** [comment]
> Do you have a plan to make some WA in OMZ requirements.in?

Unfortunately, that's not possible, because the requirements for conversion of TensorFlow models don't come from us - they come from Model Optimizer. So there's no file I could make that workaround in.

**Comment by vurusovs** [comment]
@IRDonch thank you! I'm closing the issue as resolved

**Comment by IRDonch** [comment]
I ended up adding a workaround anyway: #1831.
