### ISSUE TITLE
Error: while using opencv with inference engine

### ISSUE THREAD

**Issue by tallamtharunsai** [openvinotoolkit/open_model_zoo#2282]
I am Trying to use this code with opencv
```
import cv2

net = cv2.dnn.readNet('/opt/paralaxiom/vast/platform_openvino/backend/aimodel/models/model.xml',
                     '/opt/paralaxiom/vast/platform_openvino/backend/aimodel/models/vehicle-license-plate-detection-barrier-0106.bin')

frame = cv2.imread("/home/vast/anpr_frames/all_frames/52.jpg")

frame = cv2.resize(frame, (300,300))

blob = cv.dnn.blobFromImage(frame, size=(300, 300))
net.setInput(blob)
out = net.forward()

for detection in out.reshape(-1, 7):
    confidence = float(detection[2])
    xmin = int(detection[3] * frame.shape[1])
    ymin = int(detection[4] * frame.shape[0])
    xmax = int(detection[5] * frame.shape[1])
    ymax = int(detection[6] * frame.shape[0])

    if confidence > 0.5:
        cv.rectangle(frame, (xmin, ymin), (xmax, ymax), color=(0, 255, 0))

cv2.imwrite("/home/vast/anpr_frames/output/52.jpg",frame)
```

but I am getting this error:
```
Traceback (most recent call last):
  File "opencv_script.py", line 1, in <module>
    import cv2
  File "/opt/paralaxiom/venv/opencv_infrence_engine/lib/python3.6/site-packages/cv2/__init__.py", line 2, in <module>
    from .cv2 import *
ImportError: /opt/paralaxiom/venv/opencv_infrence_engine/lib/python3.6/site-packages/cv2/cv2.so: undefined symbol: _ZTIN15InferenceEngine14ILayerExecImplE
```

Any Suggestion?

**Comment by vladimir-dudnik** [comment]
please describe first how did you get into this environment. What OpenVINO version have you installed, how do you build execution environment to run your test. Have you try Open Model Zoo demo?
