### ISSUE TITLE
BERT Question Answering Python Demo - Input or Output names do not match

### ISSUE THREAD

**Issue by dtischler** [openvinotoolkit/open_model_zoo#2503]
Hey there, just tried to run the BERT Question Answering Python Demo, and run into an issue with the Input and Output names not matching.  Can anyone shed some light on what might be wrong here, or, if my command is not correct perhaps?  Thanks in advance!

```
root@9825fd9:/usr/src/app# python3 /opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/bert_question_answering_demo/python/bert_question_answering_demo.py --vocab=/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/models/intel/bert-large-uncased-whole-word-masking-squad-0001/vocab.txt --model=/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/bert-large-uncased-whole-word-masking-squad-0001/FP32/bert-large-uncased-whole-word-masking-squad-0001.xml --input_names="input_ids,attention_mask,token_type_ids" --output_names="output_s,output_e" --input="https://en.wikipedia.org/wiki/Bert_(Sesame_Street)" -c
[ INFO ] Loading vocab file:	/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/models/intel/bert-large-uncased-whole-word-masking-squad-0001/vocab.txt
[ INFO ] 30522 tokens loaded
[ INFO ] Get paragraphs from https://en.wikipedia.org/wiki/Bert_(Sesame_Street)
[ INFO ] Page 'Bert (Sesame Street) - Wikipedia' has 1388 chars in 5 paragraphs
[ INFO ] Size: 1392 chars
[ INFO ] Context: Bert is a yellow Muppet character on the long running PBS and HBO children's television show Sesame Street. Bert was originally performed by Frank Oz.

Since 1997, Muppeteer Eric Jacobson has been phased in as Bert's primary performer. Bert has also made cameo appearances within The Muppets franchise, including The Muppet Show, The Muppet Movie, and The Muppets Take Manhattan, in addition to an appearance with Ernie on The Flip Wilson Show on September 14, 1972, on which he sang "Clink, Clank", a song about noises.[2] Jacobson joined Sesame Street in 1994.

Bert's age is 49, but performer on Sesame Street Live, Taylor Morgan, has said that "I just kind of try to think like a six year old or a seven year old, because that's how old Bert is."[3] He and his roommate Ernie form a comic duo that is one of the program's centerpieces, with Bert acting as the world weary foil, to Ernie's naive troublemaking.

As the duo often sing in their skits, several albums were released, containing studio recorded versions of their songs. Bert's best known song is "Doin' the Pigeon". He and Ernie both had their own video, The Best of Ernie and Bert, and their own album, Bert and Ernie's Greatest Hits. Only Ernie, however, has hit the U.S. Billboard Hot 100 Chart with his song "Rubber Duckie", in September 1970.

This puppet-related article is a stub. You can help Wikipedia by expanding it.
[ INFO ] Initializing Inference Engine
[ INFO ] Plugin version is 2.1.2021.3.0-2787-60059f2c755-releases/2021/3
[ INFO ] Loading network files:
	/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/bert-large-uncased-whole-word-masking-squad-0001/FP32/bert-large-uncased-whole-word-masking-squad-0001.xml
	/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/bert-large-uncased-whole-word-masking-squad-0001/FP32/bert-large-uncased-whole-word-masking-squad-0001.bin
/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/bert_question_answering_demo/python/bert_question_answering_demo.py:148: DeprecationWarning: 'inputs' property of IENetwork class is deprecated. To access DataPtrs user need to use 'input_data' property of InputInfoPtr objects which can be accessed by 'input_info' property.
  if ie_encoder.inputs.keys() != set(input_names) or ie_encoder.outputs.keys() != set(output_names):
[ ERROR ] Input or Output names do not match
[ ERROR ]     The demo expects input->output names: ['input_ids', 'attention_mask', 'token_type_ids']->['output_s', 'output_e']. Please use the --input_names and --output_names to specify the right names (see actual values below)
[ ERROR ]     Actual network input->output names: ['0', '1', '2']->['3171', '3172']
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/bert_question_answering_demo/python/bert_question_answering_demo.py", line 305, in <module>
    sys.exit(main() or 0)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/bert_question_answering_demo/python/bert_question_answering_demo.py", line 155, in main
    raise Exception("Unexpected network input or output names")
Exception: Unexpected network input or output names
```

**Comment by vladimir-dudnik** [comment]
@dtischler You are right, in 2021.3 release bert models on OMZ has a different names of input/output blobs. We are going to change this in 2021.4 release, which is coming soon. Fortunately, bert_question_answering_demo allow to specify the names of input and output blobs as a command line parameters, see demo [description](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/bert_question_answering_demo/python/README.md) for `--input_names` and `--output_names` parameters 

|model|inputs|outputs|
|------|--------|--------|
|bert-large-uncased-whole-word-masking-squad-0001|0,1,2|3171,3172|
|bert-large-uncased-whole-word-masking-squad-int8-0001|0,1,2|result.1,result.2,result.3|
|bert-large-uncased-whole-word-masking-squad-emb-0001|input_ids,attention_mask,token_type_ids,position_ids|embedding|
|bert-small-uncased-whole-word-masking-squad-0001|input_ids,attention_mask,token_type_ids|output_s,output_e|
|bert-small-uncased-whole-word-masking-squad-emb-int8-0001|input_ids,attention_mask,token_type_ids,position_ids|embedding|
|bert-small-uncased-whole-word-masking-squad-0002|input_ids,attention_mask,token_type_ids,position_ids|output_s,output_e|
|bert-small-uncased-whole-word-masking-squad-int8-0002|input_ids,attention_mask,token_type_ids,position_ids|output_s,output_e|

**Comment by dtischler** [comment]
Thanks for the fast response @vladimir-dudnik !  

That seems to have gotten me further, yep.  Its still not quite right, but at least I overcome the Input or Output name error:

```
root@9825fd9:/usr/src/app# python3 /opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/bert_question_answering_demo/python/bert_question_answering_demo.py --vocab=/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/models/intel/bert-large-uncased-whole-word-masking-squad-0001/vocab.txt --model=//opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/bert-large-uncased-whole-word-masking-squad-0001/FP32/bert-large-uncased-whole-word-masking-squad-0001.xml --input_names="0,1,2" --output_names="3171,3172" --input="https://en.wikipedia.org/wiki/Bert_(Sesame_Street)" -c
[ INFO ] Loading vocab file:	/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/models/intel/bert-large-uncased-whole-word-masking-squad-0001/vocab.txt
[ INFO ] 30522 tokens loaded
[ INFO ] Get paragraphs from https://en.wikipedia.org/wiki/Bert_(Sesame_Street)
[ INFO ] Page 'Bert (Sesame Street) - Wikipedia' has 1388 chars in 5 paragraphs
[ INFO ] Size: 1392 chars
[ INFO ] Context: Bert is a yellow Muppet character on the long running PBS and HBO children's television show Sesame Street. Bert was originally performed by Frank Oz.

Since 1997, Muppeteer Eric Jacobson has been phased in as Bert's primary performer. Bert has also made cameo appearances within The Muppets franchise, including The Muppet Show, The Muppet Movie, and The Muppets Take Manhattan, in addition to an appearance with Ernie on The Flip Wilson Show on September 14, 1972, on which he sang "Clink, Clank", a song about noises.[2] Jacobson joined Sesame Street in 1994.

Bert's age is 49, but performer on Sesame Street Live, Taylor Morgan, has said that "I just kind of try to think like a six year old or a seven year old, because that's how old Bert is."[3] He and his roommate Ernie form a comic duo that is one of the program's centerpieces, with Bert acting as the world weary foil, to Ernie's naive troublemaking.

As the duo often sing in their skits, several albums were released, containing studio recorded versions of their songs. Bert's best known song is "Doin' the Pigeon". He and Ernie both had their own video, The Best of Ernie and Bert, and their own album, Bert and Ernie's Greatest Hits. Only Ernie, however, has hit the U.S. Billboard Hot 100 Chart with his song "Rubber Duckie", in September 1970.

This puppet-related article is a stub. You can help Wikipedia by expanding it.
[ INFO ] Initializing Inference Engine
[ INFO ] Plugin version is 2.1.2021.3.0-2787-60059f2c755-releases/2021/3
[ INFO ] Loading network files:
	//opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/bert-large-uncased-whole-word-masking-squad-0001/FP32/bert-large-uncased-whole-word-masking-squad-0001.xml
	//opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/bert-large-uncased-whole-word-masking-squad-0001/FP32/bert-large-uncased-whole-word-masking-squad-0001.bin
/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/bert_question_answering_demo/python/bert_question_answering_demo.py:148: DeprecationWarning: 'inputs' property of IENetwork class is deprecated. To access DataPtrs user need to use 'input_data' property of InputInfoPtr objects which can be accessed by 'input_info' property.
  if ie_encoder.inputs.keys() != set(input_names) or ie_encoder.outputs.keys() != set(output_names):
[ INFO ] Loading model to the CPU
Killed
root@9825fd9:/usr/src/app# 

```

So now I need to figure out why its killed, ha.

**Comment by dtischler** [comment]
BTW: This is a NUC11TNHv5, so I would assume it's a compatible CPU.

**Comment by vladimir-dudnik** [comment]
@dtischler What is the memory amount on NUC system? The model probably does not fit into the memory.

**Comment by dtischler** [comment]
Oh, interesting, I didn't even think of that!  Yes, this is a small 4gb RAM base model NUC.  I will try the FP16 next week, and report back.   :-)

**Comment by dtischler** [comment]
Closing Issue as original problem was resolved.  :-)
