### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0) when inferencing a 2 class yolov4 model

### ISSUE THREAD

**Issue by Kshitij-Khode** [openvinotoolkit/open_model_zoo#2598]
### System Information

- Docker Image Used: openvino/ubuntu18_dev:2021.3 (https://hub.docker.com/r/openvino/ubuntu18_dev)
- OpenVINO => 2021.3
- Operating System / Platform => Ubuntu 18.04 x64
- Compiler => GCC 7.5.0
- Problem classification: Model Conversion
- Framework: Model trained in Darknet, Converted to TensorFlow using https://github.com/david8862/keras-YOLOv3-model-set and then converted to OpenVINO IR using mo_tf.py
- Model name: yolov4

### Steps to Reproduce

- I trained a yolov4 darknet model (attached as yolov4_custom_best.weight) on a custom dataset. This model is a 2 class object detector with the configs provided in yolov4_custom.cfg, obj.data and obj.names.
- The yolov4_custom_best.weight got converted to yolov4_custom_best.weight.h5 and yolov4_custom_best.weight.pb using the tools/model_converter/convert.py and keras_to_tensorflow.py respectively.
- The PB model was converted to OpenVINO IR via the command: mo_tf.py. Following was the output generated.
```
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /OpenVINO-YOLOV4/frozen_darknet_yolov4_model.pb
        - Path for generated IR:        /opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/.
        - IR output name:       frozen_darknet_yolov4_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,608,608,3]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       True
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
        - Inference Engine found in:    /opt/intel/openvino/python/python3.6/openvino
Inference Engine version:       2.1.2021.3.0-2787-60059f2c755-releases/2021/3
Model Optimizer version:            2021.3.0-2787-60059f2c755-releases/2021/3
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/frozen_darknet_yolov4_model.xml
[ SUCCESS ] BIN file: /opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/frozen_darknet_yolov4_model.bin
[ SUCCESS ] Total execution time: 66.70 seconds.
[ SUCCESS ] Memory consumed: 1790 MB.
```
- A quick glance at the generated IR's XML file showed that the output layers had the following shape. This is the expected shape documented here: https://docs.openvinotoolkit.org/2021.2/omz_models_public_yolo_v4_tf_yolo_v4_tf.html
```
<layer id="668" name="conv2d_93/BiasAdd/Add" type="Add" version="opset1">
			<data auto_broadcast="numpy"/>
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>21</dim>
					<dim>76</dim>
					<dim>76</dim>
				</port>
				<port id="1">
					<dim>1</dim>
					<dim>21</dim>
					<dim>1</dim>
					<dim>1</dim>
				</port>
			</input>
			<output>
				<port id="2" precision="FP32">
					<dim>1</dim>
					<dim>21</dim>
					<dim>76</dim>
					<dim>76</dim>
				</port>
			</output>
		</layer>
		<layer id="669" name="conv2d_93/BiasAdd/Add/sink_port_0" type="Result" version="opset1">
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>21</dim>
					<dim>76</dim>
					<dim>76</dim>
				</port>
			</input>
		</layer>
```
- However, when during inference the output blob received
```
root@9b33ad7b457a:/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/object_detection_demo/python# python3 object_detection_demo.py -i /ngs_smartpark_vvps-dev/vvps/sample_images/B1.JPG -m /OpenVINO-YOLOV4/misc/convertedModels/public/myYolov4/FP32/myYolov4.xml -d CPU -at yolov4 --no_show -o test%d.jpg
[ INFO ] Initializing Inference Engine...
[ INFO ] Loading network...
[ INFO ] Reading network from IR...
[ INFO ] Loading network to CPU plugin...
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key
Traceback (most recent call last):
  File "object_detection_demo.py", line 350, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo.py", line 255, in main
    results = detector_pipeline.get_result(next_frame_id_to_show)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/common/python/pipelines/async_pipeline.py", line 66, in get_result
    return self.model.postprocess(raw_result, preprocess_meta), meta
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/common/python/models/yolo.py", line 204, in postprocess
    detections += self._parse_yolo_region(out_blob, meta['resized_shape'], layer_params[1], self.threshold)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/common/python/models/yolo.py", line 253, in _parse_yolo_region
    x, y = sigmoid(bbox[:2])
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by Kshitij-Khode** [comment]
Recently talked to @eizamaliev (Zamaliev, Eduard) from the open_model_zoo repo team and figured out the problem is with the inferencing library script: yolo.py, which has classes hardcoded to 80.

**Comment by eizamaliev** [comment]
@Kshitij-Khode See linked PR.

**Comment by vladimir-dudnik** [comment]
@Kshitij-Khode the fix should be available in the [latest](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/NEW-Intel-Distribution-of-OpenVINO-toolkit-2021-4-1-Long-Term/m-p/1313364#M25192) public OpenVINO release.
