### ISSUE TITLE
Accuracy checker sample got error.

### ISSUE THREAD

**Issue by kminemur** [openvinotoolkit/open_model_zoo#3062]
Accuracy sample tool causes dependency error

# steps
git clone this master repo.
cd open_model_zoo/tools/accuracy_checker
python setup.py install
create main.py
tar xvf cifar-10-python.tar.gz -C sample
accuracy_check -c sample/sample_config.yml -m data/test_models -s sample

I'm following https://github.com/kminemur/open_model_zoo/blob/master/tools/accuracy_checker/README.md to run accuracy sample tool.

`
tesla-23@P12HL01kminemur:~/kazuki/open_model_zoo/tools/accuracy_checker$ accuracy_check -c sample/sample_config.yml -m data/test_models -s sample
Processing info:
model: SampLeNet_example
launcher: openvino
device: CPU
dataset: sample_dataset
OpenCV version: 4.5.3-openvino
Annotation conversion for sample_dataset dataset has been started
Parameters to be used for conversion:
converter: cifar
data_batch_file: sample/cifar-10-batches-py/test_batch
convert_images: True
converted_images_dir: sample/sample_dataset/test
num_classes: 10
Annotation conversion for sample_dataset dataset has been finished
13:55:13 accuracy_checker ERROR: Requested provider openvino not registered for launcher
Traceback (most recent call last):
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/main.py", line 406, in main
    evaluator = evaluator_class.from_configs(config_entry)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py", line 87, in from_configs
    launcher = create_launcher(launcher_config, model_name, **launcher_kwargs)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/launcher.py", line 318, in create_launcher
    return Launcher.provide(
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/dependency.py", line 74, in provide
    root_provider = cls.resolve(provider)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/dependency.py", line 80, in resolve
    raise UnregisteredProviderException(name, cls.__provider_type__)
accuracy_checker.dependency.UnregisteredProviderException: Requested provider openvino not registered for launcher

`

**Comment by kminemur** [comment]
yml file config caused this issue.

After changing framework from openvino to dlsdk, no more this issue.

    launchers:
      # launcher framework (e.g. caffe, openvino)
      - framework: dlsdk

**Comment by eaidova** [comment]
@kminemur you use incompatible sample and accuracy checker versions. Obviously, you get tool from released package 2021.4 and sample from master branch. master branch is prepared for new release, where launcher has been updated. Please use the appropriate sample and tool version.
