### ISSUE TITLE
omz_downloader version conflict

### ISSUE THREAD

**Issue by bigrobinson** [openvinotoolkit/open_model_zoo#3467]
OS: Raspbian Bullseye
Python: 3.9
Following instructions from: https://www.intel.com/content/www/us/en/support/articles/000057005/boards-and-kits.html

Build was successful and environment successfully sourced. Entered OMZ demos (human_pose_estimation_3d_demo) and executed

`omz_downloader --list models.lst`

Resulting errors indicate versioning problem with omz-tools in python 3.9:

omz_downloader --list models.lst
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (omz-tools 1.0.0 (/usr/local/lib/python3.9/dist-packages/omz_tools-1.0.0-py3.9.egg), Requirement.parse('omz-tools==1.0.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bigrobinson/.local/bin/omz_downloader", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'omz-tools==1.0.1' distribution was not found and is required by the application

**Comment by andrei-kochin** [comment]
@bigrobinson  are you still experiencing this issue?
