### ISSUE TITLE
omz_downloader SSL error due to expired certificate

### ISSUE THREAD

**Issue by ojjsaw** [openvinotoolkit/open_model_zoo#3579]
========== Downloading models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml
Traceback (most recent call last):
  File "/data/venv/openvino_2022.2.0_python3.6_RC2_new/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/data/venv/openvino_2022.2.0_python3.6_RC2_new/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/data/venv/openvino_2022.2.0_python3.6_RC2_new/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/data/venv/openvino_2022.2.0_python3.6_RC2_new/lib/python3.6/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/data/venv/openvino_2022.2.0_python3.6_RC2_new/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

**Comment by eaidova** [comment]
@ojjsaw  could you please recheck? as I know issue already resolved

**Comment by ojjsaw** [comment]
Thanks, confirming it is resolved now.
