### ISSUE TITLE
Object detection demo fails for YOLO v3 onnx

### ISSUE THREAD

**Issue by ltoropova** [openvinotoolkit/open_model_zoo#3592]
Appears in OpenVINO 2022.2.0:

```
Traceback (most recent call last):
  File "/home/ltoropova/work/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 304, in <module>
    sys.exit(main() or 0)
  File "/home/ltoropova/work/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 255, in main
    detector_pipeline.submit_data(frame, next_frame_id, {'frame': frame, 'start_time': start_time})
  File "/home/ltoropova/work/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/pipelines/async_pipeline.py", line 138, in submit_data
    self.model.infer_async(inputs, callback_data)
  File "/home/ltoropova/work/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/models/model.py", line 284, in infer_async
    self.model_adapter.infer_async(dict_data, callback_data)
  File "/home/ltoropova/work/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/adapters/openvino_adapter.py", line 133, in infer_async
    self.async_queue.start_async(dict_data, (self.get_raw_result, callback_data))
  File "/home/ltoropova/work/ov/lib/python3.9/site-packages/openvino/runtime/ie_api.py", line 326, in start_async
    normalize_inputs(self[self.get_idle_request_id()], inputs), userdata,
  File "/home/ltoropova/work/ov/lib/python3.9/site-packages/openvino/runtime/ie_api.py", line 108, in normalize_inputs
    raise TypeError(f"Incompatible input data of type {type(value)} under {key} key!")
TypeError: Incompatible input data of type <class 'list'> under image_shape key!
```

The root cause seems to be that in this [PR](https://github.com/openvinotoolkit/openvino/pull/11498) function [normalize_inputs](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/runtime/ie_api.py#L85) was modified and helper function [convert_dict_items](https://github.com/openvinotoolkit/openvino/blob/2022.1.0/src/bindings/python/src/openvino/runtime/ie_api.py#L24) was removed. So input of type list can not be fed to IE. 

'image_shape' input blob should be Tensor instead of list (https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/common/python/openvino/model_zoo/model_api/models/yolo.py#L480)

**Comment by Wovchena** [comment]
Thank you for the investigation! Feel free to submit a pull request next time
