### ISSUE TITLE
yolo-v4-tf failed to convert

### ISSUE THREAD

**Issue by alexlamfromhome** [openvinotoolkit/open_model_zoo#3681]
**Relevant pkgs in environment:**
openvino                     2022.3.0
openvino-dev                 2022.3.0
openvino-telemetry           2022.3.0
tensorflow                   2.9.3
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.30.0

**Command:** 
omz_converter --name yolo-v4-tf -o models -d models

**Error message:**
==================================================================================================
Total params: 64,429,405
Trainable params: 64,363,101
Non-trainable params: 66,304
__________________________________________________________________________________________________
None
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 110). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "models/public/yolo-v4-tf/keras-YOLOv3-model-set/tools/model_converter/convert.py", line 406, in <module>
    _main(parser.parse_args())
  File "models/public/yolo-v4-tf/keras-YOLOv3-model-set/tools/model_converter/convert.py", line 389, in _main
    model.save('{}'.format(output_path))
  File "/home/alexlam/projects/omz_demo_2022.3.0/demos/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/alexlam/projects/omz_demo_2022.3.0/demos/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/graph_view.py", line 395, in _add_checkpoint_values_check
    object_proto.HasField("registered_saver")):
ValueError: Protocol message TrackableObject has no field registered_saver.
Traceback (most recent call last):
  File "/home/alexlam/projects/omz_demo_2022.3.0/demos/venv/lib/python3.8/site-packages/openvino/model_zoo/models/public/yolo-v4-tf/pre-convert.py", line 40, in <module>
    main()
  File "/home/alexlam/projects/omz_demo_2022.3.0/demos/venv/lib/python3.8/site-packages/openvino/model_zoo/models/public/yolo-v4-tf/pre-convert.py", line 30, in main
    subprocess.run([sys.executable, '--',
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/alexlam/projects/omz_demo_2022.3.0/demos/venv/bin/python3', '--', 'models/public/yolo-v4-tf/keras-YOLOv3-model-set/tools/model_converter/convert.py', 'models/public/yolo-v4-tf/keras-YOLOv3-model-set/cfg/yolov4.cfg', 'models/public/yolo-v4-tf/yolov4.weights', 'models/public/yolo-v4-tf/yolo-v4.savedmodel', '--yolo4_reorder']' returned non-zero exit status 1.

FAILED:
yolo-v4-tf

**Comment by alexlamfromhome** [comment]
Could be that I am using Ubuntu 22.04...
