### ISSUE TITLE
multi_camera_multi_target_tracking_demo

### ISSUE THREAD

**Issue by legendary111** [openvinotoolkit/open_model_zoo#3697]
l want to run the demo about multi camera and the all models are in the model.lst , but it borns wrong.
Where is the problem?
![image](https://user-images.githubusercontent.com/86969009/218629967-7d75f598-853a-4df7-b40e-3914287ed450.png)

**Comment by legendary111** [comment]
root@2fcaf328f96d:/opt/intel/openvino_2022.1.0.643/test/demos/multi_camera_multi_target_tracking_demo/python# python3 multi_camera_multi_target_tracking_demo.py -i car-detection.avi car-detection-output.avi --m_segmentation intel/instance-segmentation-security-0091/FP16/instance-segmentation-security-0091.xml --m_reid public/vehicle-reid-0001/FP16/vehicle-reid-0001.xml --no_show --output_video ./car-detection-multi.avi
[ DEBUG ] Reading config from /opt/intel/openvino_2022.1.0.643/test/demos/multi_camera_multi_target_tracking_demo/python/configs/person.py
[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ] Reading Instance Segmentation model intel/instance-segmentation-security-0091/FP16/instance-segmentation-security-0091.xml
[ INFO ] The Instance Segmentation model intel/instance-segmentation-security-0091/FP16/instance-segmentation-security-0091.xml is loaded to CPU
[ INFO ] Reading Object Reidentification model public/vehicle-reid-0001/FP16/vehicle-reid-0001.xml
[ INFO ] The Object Reidentification model public/vehicle-reid-0001/FP16/vehicle-reid-0001.xml is loaded to CPU
Traceback (most recent call last):
  File "multi_camera_multi_target_tracking_demo.py", line 284, in <module>
    sys.exit(main() or 0)
  File "multi_camera_multi_target_tracking_demo.py", line 280, in main
    run(args, config, capture, object_detector, object_recognizer)
  File "multi_camera_multi_target_tracking_demo.py", line 175, in run
    frame_size, None, **vars(config.visualization_config))
  File "/opt/intel/openvino_2022.1.0.643/test/demos/multi_camera_multi_target_tracking_demo/python/utils/visualization.py", line 52, in get_target_size
    width, height = size
ValueError: too many values to unpack (expected 2)

**Comment by legendary111** [comment]
Video source:https://[storage.openvinotoolkit.org](https://storage.openvinotoolkit.org/data/test_data/videos)/data/test_data/videos
