### ISSUE TITLE
Multi-camera Error: Input vector should be 1-D

### ISSUE THREAD

**Issue by nantanitv** [openvinotoolkit/open_model_zoo#3715]
## Context

**Environment**: Ubuntu 20.04.5 LTS
**Demo**: Multi Camera Multi Target Python*
**Detection Model**: `person-detection-retail-0013`
**Re-ID Model**: `person-reidentification-retail-0277`

## Issue

The multi-camera demo was able to process only a few frames of the video and stopped, and the last processed frame is kept displaying on the player window. Below are the command I used in the terminal, along with the output from the terminal. Both `*/FP16/*` and `*/FP32/*` versions of detection model and Re-ID model yielded the same error, if that matters.

## Input

```
python3 ./open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py \
-i /home/cav/Desktop/YOLOX/assets/back_cam/back-1.mp4 /home/cav/Desktop/YOLOX/assets/front_cam/front-1.mp4 \
--m_detector ./intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml \
--m_reid ./intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml \
--config ./open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/configs/person.py
```

## Terminal output

```bash
[ DEBUG ] Reading config from ./open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/configs/person.py
[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] Reading Object Detection model ./intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
[ INFO ] The Object Detection model ./intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml is loaded to CPU
[ INFO ] Reading Object Reidentification model ./intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
[ INFO ] The Object Reidentification model ./intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml is loaded to CPU
Traceback (most recent call last):
  File "./open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py", line 284, in <module>
    sys.exit(main() or 0)
  File "./open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py", line 280, in main
    run(args, config, capture, object_detector, object_recognizer)
  File "./open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/multi_camera_multi_target_tracking_demo.py", line 159, in run
    tracker.process(prev_frames, all_detections, all_masks)
  File "/home/cav/Desktop/ise-image-od/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/mc_tracker/mct.py", line 61, in process
    self._merge_all(all_tracks)
  File "/home/cav/Desktop/ise-image-od/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/mc_tracker/mct.py", line 66, in _merge_all
    distance_matrix = self._compute_mct_distance_matrix(all_tracks)
  File "/home/cav/Desktop/ise-image-od/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/mc_tracker/mct.py", line 117, in _compute_mct_distance_matrix
    f_avg_dist = 0.5 * cosine(track1.f_avg.get(), track2.f_avg.get())
  File "/home/cav/Desktop/ise-image-od/openvino_env/lib/python3.8/site-packages/scipy/spatial/distance.py", line 670, in cosine
    return max(0, min(correlation(u, v, w=w, centered=False), 2.0))
  File "/home/cav/Desktop/ise-image-od/openvino_env/lib/python3.8/site-packages/scipy/spatial/distance.py", line 610, in correlation
    u = _validate_vector(u)
  File "/home/cav/Desktop/ise-image-od/openvino_env/lib/python3.8/site-packages/scipy/spatial/distance.py", line 302, in _validate_vector
    raise ValueError("Input vector should be 1-D.")
ValueError: Input vector should be 1-D.
```

Thank you!

**Comment by bbartling** [comment]
Hi were you able to get this working? I notice you are using .mp4 files...I was hoping to try this on video files before trying on IP camera video stream feeding

**Comment by deadmerc** [comment]
Quick and dirty trick, at `utils/misc.py:50` change `return self.avg` to `return self.avg[0]` then demo will work

**Comment by bbartling** [comment]
How is the overall support for open VINO it doesnt seem that good if people dont respond to git issues??
