### ISSUE TITLE
RuntimeError: Device with "MYRIAD" name is not registered in the OpenVINO Runtime

### ISSUE THREAD

**Issue by openedhardware** [openvinotoolkit/open_model_zoo#3725]
OpenVINO version: `2022.3.0`
OS: `Ubuntu 20.04`, python3.8

I downloaded and converted it to IR format like the following:
```
ubuntu@ubuntu-desktop:~$ omz_downloader --name alexnet
################|| Downloading alexnet ||################

========== Downloading /home/ubuntu/public/alexnet/alexnet.prototxt
... 100%, 3 KB, 10975 KB/s, 0 seconds passed

========== Downloading /home/ubuntu/public/alexnet/alexnet.caffemodel
... 100%, 238146 KB, 2834 KB/s, 84 seconds passed

========== Replacing text in /home/ubuntu/public/alexnet/alexnet.prototxt

ubuntu@ubuntu-desktop:~$ omz_converter --name alexnet
========== Converting alexnet to IR (FP16)
Conversion command: /usr/bin/python3 -- /usr/local/bin/mo --framework=caffe --data_type=FP16 --output_dir=/home/ubuntu/public/alexnet/FP16 --model_name=alexnet --input=data '--mean_values=data[104.0,117.0,123.0]' --output=prob --input_model=/home/ubuntu/public/alexnet/alexnet.caffemodel --input_proto=/home/ubuntu/public/alexnet/alexnet.prototxt '--layout=data(NCHW)' '--input_shape=[1, 3, 227, 227]'

[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/ubuntu/public/alexnet/FP16/alexnet.xml
[ SUCCESS ] BIN file: /home/ubuntu/public/alexnet/FP16/alexnet.bin

========== Converting alexnet to IR (FP32)
Conversion command: /usr/bin/python3 -- /usr/local/bin/mo --framework=caffe --data_type=FP32 --output_dir=/home/ubuntu/public/alexnet/FP32 --model_name=alexnet --input=data '--mean_values=data[104.0,117.0,123.0]' --output=prob --input_model=/home/ubuntu/public/alexnet/alexnet.caffemodel --input_proto=/home/ubuntu/public/alexnet/alexnet.prototxt '--layout=data(NCHW)' '--input_shape=[1, 3, 227, 227]' '--layout=data(NCHW)' '--input_shape=[1, 3, 227, 227]'

[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/ubuntu/public/alexnet/FP32/alexnet.xml
[ SUCCESS ] BIN file: /home/ubuntu/public/alexnet/FP32/alexnet.bin
```

Now, I am trying to use NCS to perform image classification.

- CPU works:
```
ubuntu@ubuntu-desktop:~$ python3 open_model_zoo/demos/classification_demo/python/classification_demo.py -m public/alexnet/FP32/alexnet.xml -i Pictures/Screenshot_3.png --labels open_model_zoo/data/dataset_classes/imagenet_2012.txt
[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] Reading model public/alexnet/FP32/alexnet.xml
[ INFO ]        Input layer: data, shape: [1, 3, 227, 227], precision: f32, layout: NCHW
[ INFO ]        Output layer: prob, shape: [1, 1000], precision: f32, layout:
[ INFO ] The model public/alexnet/FP32/alexnet.xml is loaded to CPU
[ INFO ]        Device: CPU
[ INFO ]                Number of streams: 4
[ INFO ]                Number of threads: AUTO
[ INFO ]        Number of model infer requests: 5
```
- NCS doesn't work:
```
ubuntu@ubuntu-desktop:~$ python3 open_model_zoo/demos/classification_demo/python/classification_demo.py -m public/alexnet/FP16/alexnet.xml -i Pictures/Screenshot_3.png --labels open_model_zoo/data/dataset_classes/imagenet_2012.txt -d MYRIAD
[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] Reading model public/alexnet/FP16/alexnet.xml
[ INFO ]        Input layer: data, shape: [1, 3, 227, 227], precision: f32, layout: NCHW
[ INFO ]        Output layer: prob, shape: [1, 1000], precision: f32, layout:
Traceback (most recent call last):
  File "open_model_zoo/demos/classification_demo/python/classification_demo.py", line 297, in <module>
    sys.exit(main() or 0)
  File "open_model_zoo/demos/classification_demo/python/classification_demo.py", line 181, in main
    async_pipeline = AsyncPipeline(model)
  File "/home/ubuntu/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/pipelines/async_pipeline.py", line 86, in __init__
    self.model.load()
  File "/home/ubuntu/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/models/model.py", line 263, in load
    self.model_adapter.load_model()
  File "/home/ubuntu/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/adapters/openvino_adapter.py", line 65, in load_model
    self.compiled_model = self.core.compile_model(self.model, self.device, self.plugin_config)
  File "/usr/local/lib/python3.8/dist-packages/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Device with "MYRIAD" name is not registered in the OpenVINO Runtime
ubuntu@ubuntu-desktop:~$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp.
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 003: ID 03e7:2485 Intel Movidius MyriadX
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Of course, I configured the udev rule to get the NCS working...

Thank you!

**Comment by Wovchena** [comment]
Hi. I think the problem is similar to https://github.com/openvinotoolkit/open_model_zoo/issues/3703. Try building Openvino from source (branch [releases/2022/3](https://github.com/openvinotoolkit/openvino/tree/releases/2022/3)) as suggested in https://github.com/openvinotoolkit/open_model_zoo/issues/3703#issuecomment-1441274320

**Comment by openedhardware** [comment]
Thank you, @Wovchena 
That fixed this issue!
