### ISSUE TITLE
error running model on ARC 770

### ISSUE THREAD

**Issue by tarunmcom** [openvinotoolkit/open_model_zoo#3784]
I am able to run various models and examples on ARC 770 but getting error with all openvino's instense-segmentation models. Below id the error using Windows 11, Openvino 2023, python:-

```
(vino23) C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\demos\instance_segmentation_demo\python>python instance_segmentation_demo.py -m "C:\Users\arc\Downloads\intel\instance-segmentation-security-0002\FP16-INT8\instance-segmentation-security-0002.xml" -i "C:\Users\arc\Downloads\entrance_6p.mp4" --label "C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\data\dataset_classes\coco_80cl_bkgr.txt" -d GPU.1
[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2023.0.0-10926-b4452d56304-releases/2023/0
[ INFO ] Reading model C:\Users\arc\Downloads\intel\instance-segmentation-security-0002\FP16-INT8\instance-segmentation-security-0002.xml
[ INFO ]        Input layer: image, shape: [1, 3, 768, 1024], precision: f32, layout: NCHW
[ INFO ]        Output layer: 1701, shape: [0, 5], precision: f32, layout:
[ INFO ]        Output layer: 1702, shape: [0], precision: i64, layout:
[ INFO ]        Output layer: masks, shape: [0, 28, 28], precision: f32, layout:
[ INFO ] The model C:\Users\arc\Downloads\intel\instance-segmentation-security-0002\FP16-INT8\instance-segmentation-security-0002.xml is loaded to GPU.1
[ INFO ]        Number of model infer requests: 2
Traceback (most recent call last):
  File "C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\demos\instance_segmentation_demo\python\instance_segmentation_demo.py", line 258, in <module>
    sys.exit(main() or 0)
  File "C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\demos\instance_segmentation_demo\python\instance_segmentation_demo.py", line 186, in main
    pipeline.await_any()
  File "C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\demos\common\python\openvino\model_zoo\model_api\pipelines\async_pipeline.py", line 136, in await_any
    self.model.await_any()
  File "C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\demos\common\python\openvino\model_zoo\model_api\models\model.py", line 293, in await_any
    self.model_adapter.await_any()
  File "C:\Users\arc\Downloads\open_model_zoo-master\open_model_zoo-master\demos\common\python\openvino\model_zoo\model_api\adapters\openvino_adapter.py", line 147, in await_any
    self.async_queue.get_idle_request_id()
RuntimeError: Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\inference\src\infer_request.cpp:239:
Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\inference\src\dev\converter_utils.cpp:652:
Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\bindings\python\src\pyopenvino\core\async_infer_queue.cpp:148:
clFinish
```

**Comment by Wovchena** [comment]
It's likely that the problem is in GPU plugin. But I'm not sure, because the call stack fails not at inference, but at simple InferRequest manipulation. Please try running [benchmark_app.py](https://github.com/openvinotoolkit/openvino/blob/master/tools/benchmark_tool/benchmark_app.py) with the failing model. I can't reproduce it myself because I don't have dGPU.

If the error is reproduced for benchmark_app, I will transfer the issue to https://github.com/openvinotoolkit/openvino or you can submit a new issue to them yourself.
