### ISSUE TITLE
multi_camera_multi_target_tracking_demo crushes on start

### ISSUE THREAD

**Issue by MoscowskyAnton** [openvinotoolkit/open_model_zoo#3871]
Hello!
I am trying to launch multi_camera_multi_target_tracking_demo with following command:
```
python3 multi_camera_multi_target_tracking_demo.py     -i 0 2     --m_detector intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml     --m_reid intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
```

But it throws this:
```
[ DEBUG ] Reading config from /home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/configs/person.py
[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2023.1.0-12185-9e6b00e51cd-releases/2023/1
[ INFO ] Reading Object Detection model intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
[ INFO ] The Object Detection model intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml is loaded to CPU
[ INFO ] Reading Object Reidentification model intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
Traceback (most recent call last):
  File "multi_camera_multi_target_tracking_demo.py", line 284, in <module>
    sys.exit(main() or 0)
  File "multi_camera_multi_target_tracking_demo.py", line 276, in main
    object_recognizer = VectorCNN(core, args.m_reid, args.device)
  File "/home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py", line 113, in __init__
    super().__init__(core, model_path, device, 'Object Reidentification', self.max_reqs)
  File "/home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/ie_tools.py", line 25, in __init__
    self.load_model(core, model_path, device, model_type, num_reqs)
  File "/home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/ie_tools.py", line 76, in load_model
    compiled_model = core.compile_model(self.model, device)
  File "/home/anton/.local/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/core.cpp:114:
[ GENERAL_ERROR ] label is too far
```

Any ideas this comes from and how to fix that?
Using python OpenVIVO ver. 2023.1.0-12185-9e6b00e51cd-releases/2023/1 on Kubuntu 20.04
Thanks!

**Comment by Wovchena** [comment]
I can't reproduce the issue on Ubuntu. I will transfer the issue to the main repo, may be they can give a hint.

Meanwhile, just to narrow down the problem, make sure that you use the latest `person-reidentification-retail-0277`. You can download both files manually from https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/person-reidentification-retail-0277/FP16/.

Try running `python3 -c "import openvino.runtime as ov; ov.Core().compile_model('intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml', 'CPU')"` and see if it fails.
