### ISSUE TITLE
OpenVino development tools not getting installed, throwing , No module named 'distutils'.

### ISSUE THREAD

**Issue by amaancoder** [openvinotoolkit/open_model_zoo#3896]
I am using python version - 3.12.1 for windows, I am trying to install openvino Development tools using this command -  pip install openvino-dev  , also I have installed systemtools,  despite installing it I am getting this error. 

pip install openvino-dev            
Defaulting to user installation because normal site-packages is not writeable
Collecting openvino-dev
  Using cached openvino_dev-2023.2.0-13089-py3-none-any.whl.metadata (17 kB)
Collecting addict>=2.4.0 (from openvino-dev)
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting defusedxml>=0.7.1 (from openvino-dev)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting jstyleson>=0.0.2 (from openvino-dev)
  Using cached jstyleson-0.0.2.tar.gz (2.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting networkx<=3.1 (from openvino-dev)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: numpy>=1.16.6 in c:\users\amaan\appdata\roaming\python\python312\site-packages (from openvino-dev) (1.26.3)
Collecting opencv-python (from openvino-dev)
  Using cached opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting openvino-telemetry>=2022.1.0 (from openvino-dev)
  Using cached openvino_telemetry-2023.2.1-py3-none-any.whl.metadata (2.3 kB)
Collecting pillow>=8.1.2 (from openvino-dev)
  Using cached pillow-10.2.0-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting pyyaml>=5.4.1 (from openvino-dev)
  Using cached PyYAML-6.0.1-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: requests>=2.25.1 in c:\users\amaan\appdata\roaming\python\python312\site-packages (from openvino-dev) (2.31.0)
Collecting scipy>=1.8 (from openvino-dev)
  Using cached scipy-1.11.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting texttable>=1.6.3 (from openvino-dev)
  Using cached texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting tqdm>=4.54.1 (from openvino-dev)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
INFO: pip is looking at multiple versions of openvino-dev to determine which version is compatible with other requirements. This could take a while.
Collecting openvino-dev
  Using cached openvino_dev-2023.1.0-12185-py3-none-any.whl.metadata (17 kB)
  Using cached openvino_dev-2023.0.2-11065-py3-none-any.whl.metadata (17 kB)
Collecting networkx<=2.8.8 (from openvino-dev)
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting openvino-dev
  Using cached openvino_dev-2023.0.1-11005-py3-none-any.whl.metadata (17 kB)
  Using cached openvino_dev-2023.0.0-10927-py3-none-any.whl.metadata (17 kB)
  Using cached openvino_dev-2022.3.1-9227-py3-none-any.whl.metadata (18 kB)
Collecting numpy<1.25.0,>=1.16.6 (from openvino-dev)
  Using cached numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_internal\utils\misc.py", line 751, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\amaan\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\amaan\AppData\Local\Temp\pip-build-env-aug7ye8l\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

**Comment by Wovchena** [comment]
3.12 isn't supported: https://docs.openvino.ai/2023.2/openvino_docs_install_guides_install_dev_tools.html Downgrading to 3.11 should help

**Comment by Siddharth-Latthe-07** [comment]
@amaancoder To fix this issue, you need to install the `distutils` module. Since you're using Python 3.12, the recommended way to install `distutils` is by using the `ensurepip` module, which is included with Python.
You may try out these steps and do let me know, if it works
1. `python -m ensurepip --upgrade` to install setuptools which includes `disutils`
2. then install `openvino-dev` through:- `pip install openvino-dev`
let me know, if it works
thanks
