### ISSUE TITLE
Can't run object_detection_demo.py with GPU or CPU.

### ISSUE THREAD

**Issue by utility-aagrawal** [openvinotoolkit/open_model_zoo#3933]
Hi,

I am trying to run object_detection_demo.py by following this link: https://docs.openvino.ai/2024/omz_demos_object_detection_demo_python.html

Getting this error for CPU:

python3 object_detection_demo.py -d CPU  -i input_video.mp4   -m /home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/public/retinaface-resnet50-pytorch/FP32/retinaface-resnet50-pytorch.xml   -at retinaface-pytorch
[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2024.0.0-14509-34caeefd078-releases/2024/0
[ INFO ] Reading model /home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/public/retinaface-resnet50-pytorch/FP32/retinaface-resnet50-pytorch.xml
[ WARNING ] The parameter "input_size" not found in RetinaFace-PyTorch wrapper, will be omitted
[ WARNING ] The parameter "num_classes" not found in RetinaFace-PyTorch wrapper, will be omitted
[ INFO ] 	Input layer: data, shape: [1, 3, 640, 640], precision: f32, layout: NCHW
[ INFO ] 	Output layer: face_rpn_bbox_pred, shape: [1, 16800, 4], precision: f32, layout: 
[ INFO ] 	Output layer: face_rpn_cls_prob, shape: [1, 16800, 2], precision: f32, layout: 
[ INFO ] 	Output layer: face_rpn_landmark_pred, shape: [1, 16800, 10], precision: f32, layout: 
Traceback (most recent call last):
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 305, in <module>
    sys.exit(main() or 0)
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 190, in main
    detector_pipeline = AsyncPipeline(model)
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/common/python/model_zoo/model_api/pipelines/async_pipeline.py", line 86, in __init__
    self.model.load()
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/common/python/model_zoo/model_api/models/model.py", line 263, in load
    self.model_adapter.load_model()
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/common/python/model_zoo/model_api/adapters/openvino_adapter.py", line 65, in load_model
    self.compiled_model = self.core.compile_model(self.model, self.device, self.plugin_config)
  File "/home/anurag/Work/FaceRedaction/openvino_test/openvino_env/lib/python3.10/site-packages/openvino/runtime/ie_api.py", line 515, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/cpp/core.cpp:106:
Exception from src/inference/src/dev/plugin.cpp:54:
Exception from src/plugins/intel_cpu/src/config.cpp:361:
NotFound: Unsupported property CPU_BIND_THREAD by CPU plugin.

Getting this error for GPU:

python3 object_detection_demo.py -d GPU  -i input_video.mp4   -m /home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/public/retinaface-resnet50-pytorch/FP32/retinaface-resnet50-pytorch.xml   -at retinaface-pytorch
[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2024.0.0-14509-34caeefd078-releases/2024/0
[ INFO ] Reading model /home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/public/retinaface-resnet50-pytorch/FP32/retinaface-resnet50-pytorch.xml
[ WARNING ] The parameter "input_size" not found in RetinaFace-PyTorch wrapper, will be omitted
[ WARNING ] The parameter "num_classes" not found in RetinaFace-PyTorch wrapper, will be omitted
[ INFO ] 	Input layer: data, shape: [1, 3, 640, 640], precision: f32, layout: NCHW
[ INFO ] 	Output layer: face_rpn_bbox_pred, shape: [1, 16800, 4], precision: f32, layout: 
[ INFO ] 	Output layer: face_rpn_cls_prob, shape: [1, 16800, 2], precision: f32, layout: 
[ INFO ] 	Output layer: face_rpn_landmark_pred, shape: [1, 16800, 10], precision: f32, layout: 
Traceback (most recent call last):
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 305, in <module>
    sys.exit(main() or 0)
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 190, in main
    detector_pipeline = AsyncPipeline(model)
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/common/python/model_zoo/model_api/pipelines/async_pipeline.py", line 86, in __init__
    self.model.load()
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/common/python/model_zoo/model_api/models/model.py", line 263, in load
    self.model_adapter.load_model()
  File "/home/anurag/Work/FaceRedaction/openvino_test/open_model_zoo/demos/common/python/model_zoo/model_api/adapters/openvino_adapter.py", line 65, in load_model
    self.compiled_model = self.core.compile_model(self.model, self.device, self.plugin_config)
  File "/home/anurag/Work/FaceRedaction/openvino_test/openvino_env/lib/python3.10/site-packages/openvino/runtime/ie_api.py", line 515, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/cpp/core.cpp:106:
Exception from src/inference/src/dev/plugin.cpp:54:
Check 'supported' failed at src/plugins/intel_gpu/src/runtime/execution_config.cpp:110:
[GPU] Attempt to set user property GPU_THROUGHPUT_STREAMS (GPU_THROUGHPUT_AUTO) which was not registered or internal!

Can someone help? Thanks!

**Comment by Wovchena** [comment]
Fix: https://github.com/openvinotoolkit/open_model_zoo/pull/3936
